const n = 207

function fill_interfaces!!(refs::Vector{Base.RefValue{wl_interface}}, structs::Vector{Interface})
    _fill_interface!!(itf, slots) = fill_interface!!(refs, structs, itf, slots)
    for i = [4, 5, 6, 7, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45, 47, 49, 51, 52, 54, 55, 56, 63, 65, 67, 68, 70, 71, 72, 73, 74, 77, 79, 80, 81, 83, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 99, 100, 101, 102, 103, 104, 110, 111, 112, 114, 115, 116, 118, 119, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 143, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 198, 199]
        Base.unsafe_store!(interface_slots[], Ptr{Ptr{wl_interface}}(C_NULL), i)
    end
    _fill_interface!!(Interface("wl_display", 1, Message[Message("sync", "n", getptr(interface_slots[], 1)), Message("get_registry", "n", getptr(interface_slots[], 2))], Message[Message("error", "ous", getptr(interface_slots[], 3)), Message("delete_id", "u", getptr(interface_slots[], 6))]), Int[202])
    _fill_interface!!(Interface("wl_registry", 1, Message[Message("bind", "usun", getptr(interface_slots[], 7))], Message[Message("global", "usu", getptr(interface_slots[], 9)), Message("global_remove", "u", getptr(interface_slots[], 12))]), Int[2])
    _fill_interface!!(Interface("wl_callback", 1, Message[], Message[Message("done", "u", getptr(interface_slots[], 13))]), Int[1, 96])
    _fill_interface!!(Interface("wl_compositor", 4, Message[Message("create_surface", "n", getptr(interface_slots[], 14)), Message("create_region", "n", getptr(interface_slots[], 15))], Message[]), Int[203])
    _fill_interface!!(Interface("wl_shm_pool", 1, Message[Message("create_buffer", "niiiiu", getptr(interface_slots[], 16)), Message("destroy", "", getptr(interface_slots[], 1)), Message("resize", "i", getptr(interface_slots[], 22))], Message[]), Int[23])
    _fill_interface!!(Interface("wl_shm", 1, Message[Message("create_pool", "nhi", getptr(interface_slots[], 23))], Message[Message("format", "u", getptr(interface_slots[], 26))]), Int[204])
    _fill_interface!!(Interface("wl_buffer", 1, Message[Message("destroy", "", getptr(interface_slots[], 1))], Message[Message("release", "", getptr(interface_slots[], 1))]), Int[16, 89])
    _fill_interface!!(Interface("wl_data_offer", 3, Message[Message("accept", "u?s", getptr(interface_slots[], 27)), Message("receive", "sh", getptr(interface_slots[], 29)), Message("destroy", "", getptr(interface_slots[], 1)), Message("finish", "3", getptr(interface_slots[], 1)), Message("set_actions", "3uu", getptr(interface_slots[], 31))], Message[Message("offer", "s", getptr(interface_slots[], 33)), Message("source_actions", "3u", getptr(interface_slots[], 34)), Message("action", "3u", getptr(interface_slots[], 35))]), Int[48, 53, 57])
    _fill_interface!!(Interface("wl_data_source", 3, Message[Message("offer", "s", getptr(interface_slots[], 36)), Message("destroy", "", getptr(interface_slots[], 1)), Message("set_actions", "3u", getptr(interface_slots[], 37))], Message[Message("target", "?s", getptr(interface_slots[], 38)), Message("send", "sh", getptr(interface_slots[], 39)), Message("cancelled", "", getptr(interface_slots[], 1)), Message("dnd_drop_performed", "3", getptr(interface_slots[], 1)), Message("dnd_finished", "3", getptr(interface_slots[], 1)), Message("action", "3u", getptr(interface_slots[], 41))]), Int[42, 46, 58])
    _fill_interface!!(Interface("wl_data_device", 3, Message[Message("start_drag", "?oo?ou", getptr(interface_slots[], 42)), Message("set_selection", "?ou", getptr(interface_slots[], 46)), Message("release", "2", getptr(interface_slots[], 1))], Message[Message("data_offer", "n", getptr(interface_slots[], 48)), Message("enter", "uoff?o", getptr(interface_slots[], 49)), Message("leave", "", getptr(interface_slots[], 1)), Message("motion", "uff", getptr(interface_slots[], 54)), Message("drop", "", getptr(interface_slots[], 1)), Message("selection", "?o", getptr(interface_slots[], 57))]), Int[59])
    _fill_interface!!(Interface("wl_data_device_manager", 3, Message[Message("create_data_source", "n", getptr(interface_slots[], 58)), Message("get_data_device", "no", getptr(interface_slots[], 59))], Message[]), Int[205])
    _fill_interface!!(Interface("wl_shell", 1, Message[Message("get_shell_surface", "no", getptr(interface_slots[], 61))], Message[]), Int[206])
    _fill_interface!!(Interface("wl_shell_surface", 1, Message[Message("pong", "u", getptr(interface_slots[], 63)), Message("move", "ou", getptr(interface_slots[], 64)), Message("resize", "ouu", getptr(interface_slots[], 66)), Message("set_toplevel", "", getptr(interface_slots[], 1)), Message("set_transient", "oiiu", getptr(interface_slots[], 69)), Message("set_fullscreen", "uu?o", getptr(interface_slots[], 73)), Message("set_popup", "ouoiiu", getptr(interface_slots[], 76)), Message("set_maximized", "?o", getptr(interface_slots[], 82)), Message("set_title", "s", getptr(interface_slots[], 83)), Message("set_class", "s", getptr(interface_slots[], 84))], Message[Message("ping", "u", getptr(interface_slots[], 85)), Message("configure", "uii", getptr(interface_slots[], 86)), Message("popup_done", "", getptr(interface_slots[], 1))]), Int[61])
    _fill_interface!!(Interface("wl_surface", 4, Message[Message("destroy", "", getptr(interface_slots[], 1)), Message("attach", "?oii", getptr(interface_slots[], 89)), Message("damage", "iiii", getptr(interface_slots[], 92)), Message("frame", "n", getptr(interface_slots[], 96)), Message("set_opaque_region", "?o", getptr(interface_slots[], 97)), Message("set_input_region", "?o", getptr(interface_slots[], 98)), Message("commit", "", getptr(interface_slots[], 1)), Message("set_buffer_transform", "2i", getptr(interface_slots[], 99)), Message("set_buffer_scale", "3i", getptr(interface_slots[], 100)), Message("damage_buffer", "4iiii", getptr(interface_slots[], 101))], Message[Message("enter", "o", getptr(interface_slots[], 105)), Message("leave", "o", getptr(interface_slots[], 106))]), Int[14, 43, 44, 50, 62, 69, 78, 113, 117, 121, 141, 144, 158, 196, 197, 200, 201])
    _fill_interface!!(Interface("wl_seat", 7, Message[Message("get_pointer", "n", getptr(interface_slots[], 107)), Message("get_keyboard", "n", getptr(interface_slots[], 108)), Message("get_touch", "n", getptr(interface_slots[], 109)), Message("release", "5", getptr(interface_slots[], 1))], Message[Message("capabilities", "u", getptr(interface_slots[], 110)), Message("name", "2s", getptr(interface_slots[], 111))]), Int[60, 64, 66, 76])
    _fill_interface!!(Interface("wl_pointer", 7, Message[Message("set_cursor", "u?oii", getptr(interface_slots[], 112)), Message("release", "3", getptr(interface_slots[], 1))], Message[Message("enter", "uoff", getptr(interface_slots[], 116)), Message("leave", "uo", getptr(interface_slots[], 120)), Message("motion", "uff", getptr(interface_slots[], 122)), Message("button", "uuuu", getptr(interface_slots[], 125)), Message("axis", "uuf", getptr(interface_slots[], 129)), Message("frame", "5", getptr(interface_slots[], 1)), Message("axis_source", "5u", getptr(interface_slots[], 132)), Message("axis_stop", "5uu", getptr(interface_slots[], 133)), Message("axis_discrete", "5ui", getptr(interface_slots[], 135))]), Int[107])
    _fill_interface!!(Interface("wl_keyboard", 7, Message[Message("release", "3", getptr(interface_slots[], 1))], Message[Message("keymap", "uhu", getptr(interface_slots[], 137)), Message("enter", "uoa", getptr(interface_slots[], 140)), Message("leave", "uo", getptr(interface_slots[], 143)), Message("key", "uuuu", getptr(interface_slots[], 145)), Message("modifiers", "uuuuu", getptr(interface_slots[], 149)), Message("repeat_info", "4ii", getptr(interface_slots[], 154))]), Int[108])
    _fill_interface!!(Interface("wl_touch", 7, Message[Message("release", "3", getptr(interface_slots[], 1))], Message[Message("down", "uuoiff", getptr(interface_slots[], 156)), Message("up", "uui", getptr(interface_slots[], 162)), Message("motion", "uiff", getptr(interface_slots[], 165)), Message("frame", "", getptr(interface_slots[], 1)), Message("cancel", "", getptr(interface_slots[], 1)), Message("shape", "6iff", getptr(interface_slots[], 169)), Message("orientation", "6if", getptr(interface_slots[], 172))]), Int[109])
    _fill_interface!!(Interface("wl_output", 3, Message[Message("release", "3", getptr(interface_slots[], 1))], Message[Message("geometry", "iiiiissi", getptr(interface_slots[], 174)), Message("mode", "uiii", getptr(interface_slots[], 182)), Message("done", "2", getptr(interface_slots[], 1)), Message("scale", "2i", getptr(interface_slots[], 186))]), Int[75, 82, 105, 106])
    _fill_interface!!(Interface("wl_region", 1, Message[Message("destroy", "", getptr(interface_slots[], 1)), Message("add", "iiii", getptr(interface_slots[], 187)), Message("subtract", "iiii", getptr(interface_slots[], 191))], Message[]), Int[15, 97, 98])
    _fill_interface!!(Interface("wl_subcompositor", 1, Message[Message("destroy", "", getptr(interface_slots[], 1)), Message("get_subsurface", "noo", getptr(interface_slots[], 195))], Message[]), Int[207])
    _fill_interface!!(Interface("wl_subsurface", 1, Message[Message("destroy", "", getptr(interface_slots[], 1)), Message("set_position", "ii", getptr(interface_slots[], 198)), Message("place_above", "o", getptr(interface_slots[], 200)), Message("place_below", "o", getptr(interface_slots[], 201)), Message("set_sync", "", getptr(interface_slots[], 1)), Message("set_desync", "", getptr(interface_slots[], 1))], Message[]), Int[195])
end

function fill_interface_dict!(dict, interface_ptrs)
    merge!(dict, Dict{Symbol, Ptr{wl_interface}}(:wl_display => interface_ptrs[202], :wl_registry => interface_ptrs[2], :wl_callback => interface_ptrs[1], :wl_compositor => interface_ptrs[203], :wl_shm_pool => interface_ptrs[23], :wl_shm => interface_ptrs[204], :wl_buffer => interface_ptrs[16], :wl_data_offer => interface_ptrs[48], :wl_data_source => interface_ptrs[42], :wl_data_device => interface_ptrs[59], :wl_data_device_manager => interface_ptrs[205], :wl_shell => interface_ptrs[206], :wl_shell_surface => interface_ptrs[61], :wl_surface => interface_ptrs[14], :wl_seat => interface_ptrs[60], :wl_pointer => interface_ptrs[107], :wl_keyboard => interface_ptrs[108], :wl_touch => interface_ptrs[109], :wl_output => interface_ptrs[75], :wl_region => interface_ptrs[15], :wl_subcompositor => interface_ptrs[207], :wl_subsurface => interface_ptrs[195]))
end
